# author: Colin Maggard

banned_words = ['experience', 'indeed', 'cpra', 'fill', 
                'work', 'career', 'privacy', 'center',
                'browse', 'choices', 'st1', 'rule',
                'evenodd','fff','06f','required','new',
                'ability','help','related','including',
                'company','benefits','hiring','working',
                'disability',' 5 ','jobs','events','terms',
                'companies','high','life','000','salaries',
                'countries','esg','2024','st0','clip',
                'st2','st3','accessiblity','year','within',
                'dental','401', 'k','must','e','using','preferred',
                'requirements','world','employee','position',
                'equivalent','field','1','real','g','paid',
                'discovery','role','hands','day','best','across',
                'zoom','use','7','employer','3','2','based','wbd',
                'like','every','level','needs','status','get',
                'matching','etc','equal','compensation','com','warner','bros',
                'sense','batch','meet','offer','medical','bonus','provide','minimum',
                'location','practices','leave','gender','number','access','used',
                'include','range','100','external','date','esri','self','monday',
                'tuesday','wednesday','thursday','friday','saturday','according',
                'people','near','take','term','existing','become','color','looking',
                'tuition','reimbursement','x','clearance','candidate',
                'salary','race','national','origin','sexual','orientation',
                'identity','age','low','content','great','next','roles','make',
                'approaches','done','wellness','applicants','activities','commissioning','also',
                'physical','401k','4','discount','per','stay','part','individuals','able','eleven',
                'join','cross','relocation','diversity','person','preferably','secure','continuously',
                '10','ci','january','february','march','april','may','june','july',
                'august','september','october','november','december',' 0 '
                'upon','unit','marital','attitude','story','beginning','stuff','dreams','made','iconic','bringing',
                'specifically','common','ship','especially','good','religion','practice','protected','plus','duties','assigned',
                'personal','commute','holidays','referral','ba','sex','two','one','three','four',
                'five','six','seven','eight','nine','ten','sick','offers','rooms','www','look','eligibility','mental',
                'discriminate','veteran','accommodations','others','4','5','6','8','9','10','u','hour','community','hour','arrest','convictions',
                'never','need','headquartered','california','state','line','vacaville','facing','north','south','east','west','140','irving','tx','pto',
                'fully','prior','am','pm','authorized','availability','110','bereavement','know','95','backgrounds','creed','ancestry',
                'say','wizards','dragons','superheroes','even','odd','earth','beloved','characters','living','globe',
                'job','apply','application','00','pay','contact','act',' a ',' b ',' d ',' e ',' f ',' g ',' h ',' i ',' j ',' k ',' l ',' m ',' n ',
                ' o ',' p ',' q ',' s ',' t ',' u ',' v ',' w ',' x ',' y ',' z ', 'additional', 'want','https','school',
                'motorola']